# Generated by Django 4.2 on 2026-02-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_loginuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
